### PR TITLE
fix(agentic-ai): do not resolve boundary events in ad-hoc subprocess as tools

### LINKED ISSUE #4713: Agentic AI: Boundary events within ad-hoc subprocess are resolved as tools
__Describe the Bug__

When adding a boundary event to a task (tool) within an ad-hoc subprocess, the schema resolving logic used in the AI agent connector resolves the boundary event as dedicated tool.

Image

__Steps to Reproduce__

1. Add an boundary event to a tool as shown in the screenshot above
2. Use the ad-hoc tools schema connector to resolve the schema for the ad-hoc subprocess. The boundary event is listed as dedicated tool.

__Expected Behavior__

The boundary event is not listed as tool.

__Environment__

- Camunda version: 8.8.0

### PR DESCRIPTION
**Pull request by maff**
## Description

The current agentic AI tool resolving logic resolves all "root" elements (no incoming flows) within an ad-hoc subprocess as tools, which also applies to boundary events. With this change, boundary events are explicitly excluded from being resolved as tools.

## Related issues

based on #4721 

closes #4713

## Checklist

- [x] PR has a **milestone** or the `no milestone` label.

### CODE REVIEW

File: connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolverTest.java [hunk 1]
```diff
@@ -51,4 +143,88 @@ void throwsExceptionWhenAdHocSubprocessIdIsInvalid(String adHocSubprocessId) {
...
+  void throwsExceptionWhenBpmnXmlIsInvalid() {
+    when(camundaClient.newProcessDefinitionGetXmlRequest(PROCESS_DEFINITION_KEY).send().join())
+        .thenReturn("DUMMY");
+
+    assertThatThrownBy(() -> resolver.resolveSchema(PROCESS_DEFINITION_KEY, AD_HOC_SUBPROCESS_ID))
+        .isInstanceOf(ModelParseException.class);
+  }
+
+  @Test
+  void throwsExceptionWhenAdHocSubprocessIdIsInvalid() {
```
Comment (maff) [inline connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/adhoctoolsschema/resolver/CamundaClientAdHocToolsSchemaResolverTest.java:157]:
```suggestion
  void throwsExceptionWhenAdHocSubprocessWithRequestedIdDoesNotExist() {
```

**Review by mathieu-stennier — APPROVED** [review]
LGTM
