### PR TITLE
fix(idp-extraction-connector): added custom deserialization for headers map

### LINKED ISSUE #6935: IDP - FEEL annotation no longer works for outbound connectors, breaking string-to-map deserialization
## Description

PR #6210 introduced a separate `outboundConnectorObjectMapper` with `@FEEL` annotation processing disabled (`new JacksonModuleFeelFunction(false)`) to fix a conflict with intrinsic functions (#6208).

This has a side effect: any outbound connector field annotated with `@FEEL` that relied on the `FeelDeserializer` for string-to-object conversion no longer works. Jackson falls back to its default deserializers, which cannot convert a JSON string like `'{"key": "value"}'` into a `Map`.

Before #6210, there was a single `connectorObjectMapper` with `@FEEL` enabled for all connectors. The `FeelAnnotationIntrospector` registered a `FeelDeserializer` that handles JSON-string-to-map coercion. After #6210, outbound connectors use a separate ObjectMapper where this introspector is not registered.

## Impact

The IDP Extraction connector's `openAiHeaders` field (`Map<String, String>`) fails with:

```
MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap`:
no String-argument constructor/factory method to deserialize from String value
```

Other outbound connectors using `@FEEL` on `Map` fields may also be affected.

## Reports

- https://camunda.slack.com/archives/C07CTRS99KM/p1775830629228469
- https://camunda.slack.com/archives/C05FVD0AZ2R/p1775821455661249

## Timeline

| Date | Event |
|------|-------|
| Sep 2025 | `OpenAiProvider` introduced with `@FEEL` on `openAiHeaders` — **worked** |
| Jan 6, 2026 | `OpenAiRequest` introduced with `@FEEL` on `openAiHeaders` — **worked** |
| Jan 30, 2026 | [PR #6210](https://github.com/camunda/connectors/pull/6210) disabled `@FEEL` for outbound — **broke** string-to-map deserialization |

### PR DESCRIPTION
**Pull request by reiballa**
## Description

Fixes deserialization of [openAiHeaders](vscode-file://vscode-Fixes deserialization of openAiHeaders (Map<String, String>) in the IDP Extraction connector when FEEL evaluation is disabled for outbound connectors.

Since PR #6210 introduced a separate outboundConnectorObjectMapper with `@feel` processing disabled, Map-typed fields that arrive as JSON strings can no longer rely on the `FeelDeserializer` to coerce them. This caused a `MismatchedInputException` at runtime.

**Testing:**

* Added `StringToMapDeserializerTest` to verify correct deserialization from both JSON objects and strings, and to ensure invalid inputs are properly rejected.

## Related issues

closes https://github.com/camunda/connectors/issues/6935

## Checklist

- [x] Backport labels are added if these code changes should be backported. No backport label is added to the latest
  release, as this branch will be rebased onto main before the next release. Example backport labels:
    - `backport stable/8.8`: for changes that should be included in the next 8.8.x release.
    - **or** `backport release-8.8.7`: for changes that should be included in the specific release 8.8.7, and this
      *release has already been created*. The release branch will be merged back into stable/8.8 later, so the change
      will be included in future 8.8.x releases as well.
- [x] Tests/Integration tests for the changes have been added if applicable.
- [x] If the change requires a documentation update, it has been added to the appropriate section in the documentation.

### CODE REVIEW

File: connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/client/ai/OpenAiClient.java [hunk 1]
```diff
@@ -37,4 +39,24 @@ public OpenAiClient(String endpoint, Map<String, String> headers, ConverseData c
...
+    for (var entry : headers.entrySet()) {
+      String value = entry.getValue();
+      sanitized.put(entry.getKey(), value != null ? sanitizeHeaderValue(value) : null);
+    }
+    return sanitized;
+  }
+
+  private static String sanitizeHeaderValue(String value) {
+    // Replace non-ASCII characters (e.g. U+2028 Line Separator from copy-paste) with spaces
+    return value.replaceAll("[^\\x09\\x20-\\x7E\\x80-\\xFF]", " ").strip();
```
Comment (steven-rg-harrison) [inline connectors/idp-extraction/src/main/java/io/camunda/connector/idp/extraction/client/ai/OpenAiClient.java:66]: 🔧 I think this method should handle the null/blank validation rather than assuming it is happening prior.

```
if (StringUtils.isBlank(value)) {
    return null;
}
```

Then we can replace
```
sanitized.put(entry.getKey(), value != null ? sanitizeHeaderValue(value) : null);
```
with
```
sanitized.put(entry.getKey(), sanitizeHeaderValue(value));
```

**Review by steven-rg-harrison — APPROVED** [review]
One minor comment, but not a blocker
