### PR TITLE
fix(agentic-ai): Normalize AI agent document content type by lowercasing and trimming

### LINKED ISSUE #7009: AI agent is failing to upload images with non-lowercased mime types to OpenAI
__Describe the Bug__

  When using the AI Agent  with an OpenAI model, providing a user input document whose `Content-Type` metadata is not lowercased
  (e.g. `IMAGE/JPEG`) causes the OpenAI API to reject the request with:

  ```json
  {
    "message": "Invalid MIME type. Only image types are supported.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_image_format"
  }
  ```

  The same document works fine with Anthropic models.

  In `DocumentToContentConverterImpl#getContentType` the content type is parsed from the document metadata but not normalized, so the original casing is forwarded to the LLM provider.

  __Steps to Reproduce__

  1. Configure an AI Agent Task / sub process against an OpenAI model.
  2. Send a user message with a document whose `Content-Type` metadata is upper- or mixed-case (e.g. `IMAGE/JPEG`).
  3. Call to OpenAI fails with the error above. Same document against an Anthropic model works.

  __Expected Behavior__

  Documents should be forwarded to the LLM provider with a normalized mime type so behavior is consistent across providers regardless of the casing
  set by the uploading client.

  __Environment__

  - OS: any
  - Library version: connectors-bundle / agentic-ai (LangChain4j 1.12.2)
  - Camunda version: 8.8
  - Affected code: `connectors/agentic-ai/.../DocumentToContentConverterImpl.java` — `getContentType(...)`

### PR DESCRIPTION
**Pull request by nikonovd**
## Description

Some providers, like OpenAI do not allow content types for e.g. images to be uppercased, i.e. `IMAGE/PNG`.
Thus, the content type is normalized for AI agent document inputs by lowercasing and trimming them.

## Related issues

closes #7009

## Checklist

- [x] Backport labels are added if these code changes should be backported. No backport label is added to the latest
  release, as this branch will be rebased onto main before the next release. Example backport labels:
    - `backport stable/8.8`: for changes that should be included in the next 8.8.x release.
    - **or** `backport release-8.8.7`: for changes that should be included in the specific release 8.8.7, and this
      *release has already been created*. The release branch will be merged back into stable/8.8 later, so the change
      will be included in future 8.8.x releases as well.
- [x] Tests/Integration tests for the changes have been added if applicable.
- [ ] If the change requires a documentation update, it has been added to the appropriate section in the documentation.

### CODE REVIEW

File: connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/document/DocumentToContentConverterTest.java [hunk 1]
```diff
@@ -120,6 +121,23 @@ void convertsToImageFileContent(String mediaType) {
...
+    when(document.asBase64()).thenReturn(DUMMY_B64_VALUE);
+
+    var content = converter.convert(document);
+
+    assertThat(content)
+        .asInstanceOf(InstanceOfAssertFactories.type(ImageContent.class))
+        .satisfies(
+            imageContent -> {
+              assertThat(imageContent.image().mimeType())
+                  .isEqualTo(contentType.toLowerCase(Locale.ROOT).trim());
```
Comment (maff) [inline connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/document/DocumentToContentConverterTest.java]: 🔧 Should we compare to the actual expected output  `image/png` instead of repeating the logic here?

**Review by maff — APPROVED** [review]

File: connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/document/DocumentToContentConverterTest.java (hunk 1 above)
Comment (nikonovd) [reply connectors/agentic-ai/src/test/java/io/camunda/connector/agenticai/aiagent/framework/langchain4j/document/DocumentToContentConverterTest.java]: Valid point, i applied the suggestion 👍
