### PR TITLE
test(agentic-ai): fix flaky e2e document handling tests

### LINKED ISSUE #4950: Agentic AI: Investigate flaky e2e tests involving documents
__Describe the Bug__

Agentic AI tests involving document references (either as input documents or as tool call results) sometimes fail, because the HTTP response can't be parsed when loading the document:

```
'AI_Agent' [type: JOB_NO_RETRIES] "Failed to convert result of tool call 'Download_A_File' to string: Failed to read document content: io.camunda.client.api.command.ClientException: org.apache.hc.core5.http.ParseException: Invalid header: <: >"
```

Example CI run: https://github.com/camunda/connectors/actions/runs/15770535252/job/44454550021

__Steps to Reproduce__

Run the following tests until they eventually fail (e.g. with IntelliJ - Repear until failure):

- `Langchain4JAiAgentUserPromptDocumentsTests`
- `Langchain4JAiAgentToolCallingTests#supportsDocumentResponsesFromToolCalls`

__Expected Behavior__

Tests never run into the error described above.

__Environment__

Connectors latest `main` branch.

### PR DESCRIPTION
**Pull request by maff**
## Description

Attempts to fix the e2e tests involving document handling by using an in memory document store, similar to what we already do in `connectors-e2e-test-http`.

## Related issues

closes #4950 

## Checklist

- [x] PR has a **milestone** or the `no milestone` label.

### CODE REVIEW

File: connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/BaseLangchain4JAiAgentTests.java [hunk 1]
```diff
@@ -88,14 +91,26 @@ abstract class BaseLangchain4JAiAgentTests extends BaseAiAgentTest {
...
+  @TestConfiguration
+  static class CamundaDocumentTestConfiguration {
+
+    @Bean
+    @Primary
+    public CamundaDocumentStore camundaDocumentStore() {
+      return InMemoryDocumentStore.INSTANCE;
+    }
+  }
+
```
Comment (maff) [inline connectors-e2e-test/connectors-e2e-test-agentic-ai/src/test/java/io/camunda/connector/e2e/agenticai/aiagent/langchain4j/BaseLangchain4JAiAgentTests.java:103]: Similar to what we already do in `connectors-e2e-test-http`.

File: connector-sdk/document/src/main/java/io/camunda/document/store/InMemoryDocumentStore.java [hunk 2]
```diff
@@ -55,6 +55,10 @@ public String getContentType() {
 
           @Override
           public OffsetDateTime getExpiresAt() {
+            if (request.timeToLive() != null) {
+              return OffsetDateTime.now().plus(request.timeToLive());
+            }
+
             return null;
```
Comment (maff) [inline connector-sdk/document/src/main/java/io/camunda/document/store/InMemoryDocumentStore.java:62]: Not sure if this returned always `null` on purpose or was just never implemented. Now it should behave as the API.

**Review by reiballa — APPROVED** [review]
LGTM
