### PR TITLE
fix(kafka): Handle consumerGroup properly + update the offset override part

### LINKED ISSUE #2846: Kafka inbound connector creates 2 processes for 1 message
__Describe the Bug__

If there are multiple connector runtimes, one message is correlated twice, and therefore 2 process instances are created instead of 1.

Support ticket: https://jira.camunda.com/browse/SUPPORT-22763

__Steps to Reproduce__

1. Deploy a process definition with a Kafka consumer
2. Send a Kafka message to the specific topic
3. Observe that multiple process instances are created

__Expected Behavior__

Only one process instance should be created for one Kafka message.

__Environment__

Every runtime with a replica node.

### PR DESCRIPTION
**Pull request by johnBgood**
## Description

- Fix the way we handle consumerGroups
  - The `assign` method that we used was overriding Kafka's consumer group mechanism (silently). We now use `subscribe` instead.
- Update the way we handle manual offsets.
- Update UTs.

## Related issues

closes #2846

### CODE REVIEW

File: connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java [hunk 1]
```diff
@@ -52,27 +53,35 @@
...
+        Arguments.of(Arrays.asList(10L, 12L), Arrays.asList(10L, 12L)));
+  }
 
   @BeforeEach
   @SuppressWarnings("unchecked")
   public void setUp() {
-    topic = "my-topic";
-    topicPartitions =
+    String topic = "my-topic";
+    List<PartitionInfo> topicPartitions =
```
Comment (markfarkas-camunda) [inline connectors/kafka/src/test/java/io/camunda/connector/kafka/inbound/KafkaExecutableTest.java:84]: The CodeQL scan is right, we don't use this variable anymore.

**Review by markfarkas-camunda — COMMENTED** [review]
I am not sure yet why, but integration tests are consistently failing for me on my local machine. Could you please check if you can run them?

**Review by sbuettner — APPROVED** [review]
