### PR TITLE
Kafka connector loop retry

### LINKED ISSUE #2750: Kafka inbound connector stops processing messages on any error
__Describe the Bug__

The Kafka inbound connector stops processing messages in case of any error. To resume message processing, the user has to redeploy the process.

Because of this behavior, even if the user manually edits the offsets for the consumer group used by the connector, the connector won't be able to recover from this situation.

__Steps to Reproduce__

1. Initialize an inbound Kafka connector
2. Publish a message to the topic that contains invalid JSON, or simply doesn't match the activation condition specified in the connector
3. Check the connector runtime logs, activity logs in the web modeler, and make sure that the consumer was stopped

__Expected Behavior__

The connector should retry after a certain backoff period (e.g. 30 seconds). The external consequences may lead to offsets changing, or the activation condition starting to evaluate to true, so the connector should be able to recover.

__Environment__

- all versions <=8.6-alpha2.1

### PR DESCRIPTION
**Pull request by chillleader**
## Description

Adds retries to the Kafka connector consumer loop.

Previously, when the consumer threw an exception, it just stopped processing until the process is redeployed. The new default is to retry this as long as the connector is active, with a backoff of 30 seconds.

## Related issues

closes #2750

### CODE REVIEW

**Review by johnBgood — DISMISSED** [review]
Really nice!

File: connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java [hunk 1]
```diff
@@ -63,13 +65,23 @@ public class KafkaExecutable implements InboundConnectorExecutable<InboundConnec
...
   }
 
   public KafkaExecutable() {
-    this(KafkaConsumer::new);
+    this(
+        KafkaConsumer::new,
+        RetryPolicy.builder()
+            .handle(Exception.class)
+            .withDelay(Duration.ofSeconds(30))
+            .withMaxAttempts(-1)
```
Comment (johnBgood) [inline connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java:83]: maybe having a constant here to express the meaning: INFINITE or similar (if this is what -1 means)

**Review by johnBgood — APPROVED** [review]
1 minor comment only 👍

File: connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java (hunk 1 above)
Comment (chillleader) [reply connectors/kafka/src/main/java/io/camunda/connector/kafka/inbound/KafkaExecutable.java]: Good point!

**Review by sbuettner — APPROVED** [review]

**Comment by sbuettner** [comment]
@chillleader This one might require e2e test fixes.

**Comment by chillleader** [comment]
@sbuettner this should have fixed the test

**Review by johnBgood — APPROVED** [review]

**Review by sbuettner — APPROVED** [review]
