### PR TITLE
fix(feel-wrapper): Handle primitive types in FEEL expressions

### LINKED ISSUE #2098: `FeelEngineWrapperException` when connector returns a primitive type
__Describe the Bug__

The outboundConnectorFunction's execute method returns a simple value such as a String or any other Object-wrapper type of a primitive type. This works as long as you do not use a result or error expression. If you do, then an `io.camunda.connector.feel.FeelEngineWrapperException` is thrown.

This caused by the `ConnectorJobHandler` calling the `ConnectorHelper`, which calls `FeelEngineWrapper.evaluateToJson()`.

__Steps to Reproduce__

1. Create a diagram with a Connector that returns a single string value, not wrapped into an object
2. Use the result expression or error expression on the response value

__Expected Behavior__

Result expression and error expression should be able to handle primitive return values.

### PR DESCRIPTION
**Pull request by johnBgood**
## Description

Previously we [failed](https://github.com/camunda/connectors/blob/main/connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java#L102) when a variable was not convertible to a Map.

Instead of failing, we will now silently ignore variables that are not convertible. 
This will allow the connectors to return primitives, and the result is added to the [response](https://github.com/camunda/connectors/blob/5c1577352bf5c043dade881ecadae4d20e0e783c/connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapperUtil.java#L23) object.

## Related issues

closes #2098

### CODE REVIEW

File: connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java [hunk 1]
```diff
@@ -51,12 +51,23 @@
 
 class ConnectorJobHandlerTest {
 
+  private record TestConnectorResponsePojo(String value) {}
+
+  private static class NonSerializable {
+
+    private final UUID field = UUID.randomUUID();
+  }
+
```
Comment (johnBgood) [inline connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java:60]: just re ordered, ignore that

File: connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java [hunk 2]
```diff
@@ -51,12 +51,23 @@
...
   @Nested
   class OutputTests {
 
     @Nested
     class ResultVariableTests {
 
+      protected static ConnectorJobHandler newConnectorJobHandler(OutboundConnectorFunction call) {
+        return new ConnectorJobHandler(call, e -> {});
+      }
+
```
Comment (johnBgood) [inline connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java:70]: same here

File: connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java [hunk 3]
```diff
@@ -343,6 +350,22 @@ void shouldNotFail_MappingNonExistingKeys() {
...
+        var resultExpression = "{processedOutput: response}";
+
+        // when
+        var result =
+            JobBuilder.create()
+                .withResultExpressionHeader(resultExpression)
+                .executeAndCaptureResult(jobHandler);
+
+        // then
+        assertThat(result.getVariables()).isEqualTo(Map.of("processedOutput", "FOO"));
```
Comment (johnBgood) [inline connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java:366]: please confirm this is what is expected when a Connector return "FOO" for instance

File: connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java [hunk 4]
```diff
@@ -93,13 +94,13 @@ private static scala.collection.immutable.Map<String, Object> toScalaMap(
...
 
-  private Map<String, Object> ensureVariablesMap(final Object[] variables) {
+  private Map<String, Object> mergeMapVariables(final Object[] variables) {
     try {
       Objects.requireNonNull(variables, ERROR_CONTEXT_IS_NULL);
       Map<String, Object> variablesMap = new HashMap<>();
       for (Object o : variables) {
         Objects.requireNonNull(o, ERROR_CONTEXT_IS_NULL);
-        variablesMap.putAll(objectMapper.convertValue(o, MAP_TYPE_REFERENCE));
+        tryConvertToMap(o).ifPresent(variablesMap::putAll);
```
Comment (johnBgood) [inline connector-sdk/feel-wrapper/src/main/java/io/camunda/connector/feel/FeelEngineWrapper.java:103]: we know ignore values that are not convertible to `MAP_TYPE_REFERENCE`

File: connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java [hunk 5]
```diff
@@ -201,7 +201,7 @@ void feelFunctionDeserialization_contextAware_mergedWithInput() throws IOExcepti
   }
 
   @Test
-  void feelFunctionDeserlization_contextAware_knowsJava8Time() throws IOException {
+  void feelFunctionDeserialization_contextAware_knowsJava8Time() throws IOException {
```
Comment (sbuettner) [inline connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java:204]: Do these changes come from the autoformatting or are they intentional?

File: connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java (hunk 3 above)
Comment (sbuettner) [reply connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java:366]: you can also add a test where the same applies for a scalar value when using a result variable.

File: connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java (hunk 5 above)
Comment (johnBgood) [reply connector-sdk/jackson-datatype-feel/src/test/java/io/camunda/connector/feel/jackson/FeelFunctionDeserializerTest.java:204]: I just fixed the typo here

File: connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java (hunk 3 above)
Comment (johnBgood) [reply connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java:366]: Isn't it [this](https://github.com/camunda/connectors/blob/9216c5f1e9042098ed6192dc4bbd246c4a9171ed/connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java#L137) test?

Comment (sbuettner) [reply connector-runtime/connector-runtime-core/src/test/java/io/camunda/connector/runtime/core/outbound/ConnectorJobHandlerTest.java:366]: Yes, right. Wasnt aware that its already present.

**Review by sbuettner — APPROVED** [review]

**Comment by johnBgood** [comment]
Backport PR for release/8.4 https://github.com/camunda/connectors/pull/2227

**Comment by sbuettner** [comment]
@johnBgood As we are still on 8.5 in our `main` branch you dont have to backport it. It will be part of the release when we rebase `main` into the `release/8.5` branch.
